version: "3.9"

networks: 
  platform:
    name: platform
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 
          gateway: 172.20.0.1
          
volumes: 
  nexus-data:
    name: nexus-data
  gitlab-config:
    name: gitlab-config
  gitlab-data:
    name: gitlab-data
  gitlab-logs:
    name: gitlab-logs
  elasticsearch-data:
    name: elasticsearch-data